- name: Download consul binary
  get_url:
    url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
    dest: /tmp
    mode: 0440

- name: Install required packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/consul_{{consul_version}}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755

# Retrieve host ip with check with interface returns an ip
# BE CAREFUL! this may not  work if multiple network names are availiable
- set_fact:
    host_ip: "{{hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']}}"
  when: hostvars[inventory_hostname]['ansible_enp0s8'] is defined

- set_fact:
    host_ip: "{{hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address']}}"
  when: hostvars[inventory_hostname]['ansible_eth0'] is defined