- name: Ensure consul {{consul_agent_type}} start script is copied to host
  template:
    src: consul-{{consul_agent_type}}.service.j2
    dest: /etc/systemd/system/consul-{{consul_agent_type}}.service

- name: Ensure service consul-{{consul_agent_type}}.service is started
  systemd:
    state: started
    daemon_reload: yes
    name: consul-{{consul_agent_type}}.service

- set_fact:
    consul_server_ip: "{{host_ip}}"
  when: consul_agent_type == 'server'
