- hosts: node1
  gather_facts: False
  tasks:
    - import_role:
        name: python2

- hosts: node1 
  tasks:
    - import_role:
        name: docker

- hosts: node1
  tasks:
    - import_role:
        name: rabbitmq
      tags: rabbitmq