- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: python2
    tags: python2

- hosts: all
  tasks:
  - import_role:
      name: docker
    tags: docker
  - import_role:
      name: node-metrics-exporter
    tags: node-metrics-exporter
  - import_role:
      name: consul
    tags: consul
  - import_role:
      name: registrator
    tags: registrator
  - import_role:
      name: traefik
    tags: traefik



- hosts: dns
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always

- hosts: jobmanager
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: rabbitmq
    tags: rabbitmq
  - import_role:
      name: rabbitmq-test
    tags: rabbitmq-test
    
- hosts: worker-node-1
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: worker-calculation
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    tags: worker-read-data

- hosts: monitoring
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: monitoring
    tags: monitoring

- hosts: nfs
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: nfs
    tags: nfs
