- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: python2
    tags: python2

- hosts: all
  tasks:
  - import_role:
      name: docker
    tags: docker
  - import_role:
      name: node-metrics-exporter
    tags: node-metrics-exporter

- hosts: dns
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: consul
    vars:
      consul_agent_type: server
    tags: consul

- hosts: jobmanager
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
    tags: consul
  - import_role:
      name: rabbitmq
    tags: rabbitmq
  - import_role:
      name: rabbitmq-test
    tags: rabbitmq-test
    
- hosts: worker-node-1
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
    tags: consul
  - import_role:
      name: worker-calculation
    vars:
      worker_instance_count: 1
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    vars:
      worker_instance_count: 1
    tags: worker-read-data

- hosts: monitoring
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
    tags: consul
  - import_role:
      name: monitoring
    tags: monitoring

- hosts: nfs
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always
  - debug: var=hostvars['dns']['consul_server_ip']
    when: hostvars['dns']['consul_server_ip'] is defined
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
    tags: consul
  - import_role:
      name: nfs
    tags: nfs
