- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: python2
    tags: python2

- hosts: all
  tasks:
  - import_role:
      name: docker
    tags: docker
  - import_role:
      name: node-metrics-exporter
    tags: node-metrics-exporter
  - import_role:
      name: registrator
    tags: registrator

- hosts: dns
  tasks:
  - import_role:
      name: consul
    vars:
      consul_agent_type: server
    tags: consul

- hosts: all:!dns
  tasks:
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
    tags: consul

- hosts: jobmanager
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: rabbitmq
    tags: rabbitmq
  - import_role:
      name: rabbitmq-test
    tags: rabbitmq-test
    
- hosts: worker_node_1,worker_node_2
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: worker-calculation
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    tags: worker-read-data
  - import_role:
      name: worker-optimization
    tags: worker-optimization

- hosts: monitoring
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: monitoring
    tags: monitoring

- hosts: nfs
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: nfs
    tags: nfs
