- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: python2
    tags: python2
  - import_role:
      name: docker
    tags: docker

- hosts: jobmanager
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: monitoring
    tags: monitoring
  - import_role:
      name: rabbitmq
    tags: rabbitmq
  - pause:
      seconds: 20
  - import_role:
      name: rabbitmq-test
    tags: rabbitmq-test
    
- hosts: worker-node-1
  tasks: 
  - import_role:
      name: worker-calculation
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    tags: worker-read-data