- hosts: all
  gather_facts: False
  tasks:
  - import_role:
      name: python2
    tags: python2

- hosts: dns
  tasks:
  - import_role:
      name: consul
    tags: consul

- hosts: all:!dns
  tasks:
  - import_role:
      name: consul
    vars:
      consul_agent_type: agent
      consul_server_ip: "{{ hostvars['dns']['ansible_host'] }}"
    tags: consul

- hosts: nodes
  tasks: 
  - import_role:
      name: docker
    tags: docker
  - import_role:
      name: metrics-node
    tags: metrics-node
  - import_role:
      name: metrics-cadvisor
    tags: metrics-cadvisor
  - import_role:
      name: metrics-consul
    tags: metrics-consul
  - import_role:
      name: registrator
    tags: registrator
  - import_role:
      name: traefik
    tags: traefik


- hosts: monitoring
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: monitoring
    tags: monitoring

- hosts: nfs
  tasks:
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: nfs
      tasks_from: server
    tags: nfs

- hosts: jobmanager
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: rabbitmq
    tags: rabbitmq
    
- hosts: worker-node-1
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: nfs
      tasks_from: client
    tags: nfs
  - import_role:
      name: worker-calculation
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    tags: worker-read-data
  - import_role:
      name: worker-optimization
    tags: worker-optimization


- hosts: worker-node-2
  tasks: 
  - include_vars:
      file: credentials.yml
    tags: always
  - import_role:
      name: nfs
      tasks_from: client
    tags: nfs
  - import_role:
      name: worker-calculation
    tags: worker-calculation
  - import_role:
      name: worker-read-data
    tags: worker-read-data
  - import_role:
      name: worker-optimization
    tags: worker-optimization