- hosts: node-1
  gather_facts: False
  tasks:
    - import_role:
        name: python2

- hosts: node-1
  tasks: 
    - include_vars:
        file: credentials.yml
    - import_role:
        name: rabbitmq
    - pause:
        seconds: 20
    - import_role:
        name: rabbitmq-test

