- name: Ensure rabbitmq start script is copied to host
  template:
    src: start.sh
    dest: /tmp/start.sh
    mode: u+x

- name: Ensure that rabbitmq_data volume is present
  docker_volume:
    name: rabbitmq_data

- name: Ensure jobmanager network is present
  docker_network:
    name: jobmanager_network

- name: Ensure rabbitmq container is started
  docker_container:
    name: rabbitmq
    image: inowas/rabbitmq
    hostname: "{{ hostname }}"
    ports: "{{ port_list }}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - /tmp/start.sh:/start.sh
    networks:
      - name: jobmanager_network
    state: started
    recreate: yes
    command: /start.sh
