- name: Ensure rabbitmq start script is copied to host
  template:
    src: start.sh
    dest: /tmp/start.sh

- name: Create jobmanager network
  docker_network:
    name: jobmanager_network

- name: Ensure rabbitmq container is started
  docker_container:
    name: rabbitmq
    image: deadtrickster/rabbitmq_prometheus
    hostname: "{{ hostname }}"
    ports: "{{ port_list }}"
    volumes:
      - /tmp/start.sh:/start.sh
    networks:
      - name: jobmanager_network
    state: started
    recreate: yes
    command: /start.sh
