- name: Ensure rabbitmq configuration data is copied to host
  copy:
    src: rabbitmq-data/
    dest: /srv/rabbitmq


- name: Ensure rabbitmq start script is copied to host
  template:
    src: start.sh
    dest: /srv/rabbitmq/start.sh
    mode: u+x

- name: Ensure that rabbitmq_data volume is present
  docker_volume:
    name: rabbitmq_data

- import_role:
    name: get_host_ip

- name: Ensure rabbitmq container is started
  docker_container:
    name: rabbitmq
    image: inowas/rabbitmq
    hostname: "{{ hostname }}"
    ports: 
    - 5672:5672
    - 5671:5671
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    - /srv/rabbitmq:/data
    - /srv/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    env:
      SERVICE_15672_NAME: "{{ app_name }}"
      SERVICE_5672_NAME: rabbitmq-tcp
      SERVICE_5671_NAME: rabbitmq-tls
      SERVICE_15671_IGNORE: true
      SERVICE_25672_IGNORE: true
      SERVICE_4369_IGNORE: true
      SERVICE_TAGS: "metrics-rabbitmq"
    labels:
      traefik.frontend.rule: "Host:{{ app_name }}.{{consul_service_domain}}"
      traefik.port: "15672"
      host.ip: "{{ host_ip }}"
    state: started
    recreate: yes
    
    command: /data/start.sh

- import_role:
    name: rabbitmq-test