- name: Ensure datasource configuration is copied to host
  copy:
    src: datasource.yml
    dest: /tmp/datasource.yml

- name: Ensure dashboards configuration is copied to host
  copy:
    src: dashboards.yml
    dest: /tmp/dashboards.yml

- name: Ensure dashboard configurations directory is copied to host
  copy:
    src: dashboards/
    dest: /tmp/dashboards/

- name: Ensure grafana container is started
  docker_container:
    name: grafana
    image: grafana/grafana
    ports: "{{ grafana_port_list }}"
    volumes:
    - /tmp/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    - /tmp/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - /tmp/dashboards/:/var/lib/grafana/dashboards/
    networks:
    - name: jobmanager_network
    state: started
    recreate: yes
