- name: Ensure grafana configuration data is copied to host
  copy:
    src=grafana-data/
    dest=/srv/{{ grafana_app_name }}

- name: Ensure grafana datasource config is copied to host
  template:
    src: datasource.yml.j2
    dest: /srv/{{ grafana_app_name }}/datasource.yml

- name: Ensure grafana container is started and optionally recreated ({{ docker_recreate }})
  docker_container:
    name: "{{ grafana_app_name }}"
    image: grafana/grafana
    recreate: "{{ docker_recreate }}"
    restart_policy: unless-stopped
    volumes:
    - /srv/{{ grafana_app_name }}/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    - /srv/{{ grafana_app_name }}/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - /srv/{{ grafana_app_name }}/dashboards/:/var/lib/grafana/dashboards/
    state: started
    dns_servers:
    - "{{ consul_agent_ip }}"
    env:
      SERVICE_TAGS: "metrics-dns"
      SERVICE_9090_NAME: "{{ grafana_app_name }}"
    labels:
      traefik.frontend.rule: "Host:{{ grafana_app_name }}.{{consul_service_domain}}"
      host.ip: "{{ host_ip }}"