- name: Create jobmanager network
  docker_network:
    name: jobmanager_network

- name: Ensure grafana container is started
  docker_container:
    name: grafana
    image: grafana/grafana
    ports: "{{ grafana_port_list }}"
    networks:
      - name: jobmanager_network
    state: started
    restart: yes
