- name: Ensure prometheus configuration data is copied to host
  copy:
    src=prometheus-data/
    dest=/srv/{{ prometheus_app_name }}

- name: Ensure prometheus config is copied to host
  template:
    src: prometheus.yml.j2
    dest: /srv/{{ prometheus_app_name }}/prometheus.yml

- name: Ensure that prometheus_data volume is present
  docker_volume:
    name: prometheus_data
 
- name: Ensure prometheus container is started and optionally recreated ({{ docker_recreate }})
  docker_container:
    name: "{{ prometheus_app_name }}"
    image: prom/prometheus
    state: started
    recreate: "{{ docker_recreate }}"
    restart_policy: unless-stopped
    dns_servers:
    - "{{ consul_agent_ip }}"
    volumes:
      - /srv/{{ prometheus_app_name }}:/config
      - prometheus_data:/prometheus
    env:
      SERVICE_TAGS: "metrics-dns"
      SERVICE_9090_NAME: "{{ prometheus_app_name }}"
    labels:
      traefik.frontend.rule: "Host:{{ prometheus_app_name }}.{{consul_service_domain}}"
      host.ip: "{{ host_ip }}"
    command: --config.file=/config/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention=30d
