- name: Ensure prometheus server configuration is copied to host
  template:
    src=prometheus.yml.j2
    dest=/tmp/prometheus.yml

- name: Create jobmanager network
  docker_network:
    name: jobmanager_network

- name: Ensure prometheus container is started
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports: "{{ prometheus_port_list }}"
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - name: jobmanager_network
    state: started
    restart: yes
