- name: Ensure prometheus server configuration is copied to host
  copy:
    src=prometheus.yml
    dest=/tmp/prometheus.yml

- name: Ensure prometheus container is started
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports: "{{ prometheus_port_list }}"
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - name: jobmanager_network
    state: started
    recreate: yes
