- name: Ensure required packages for nfs client are installed
  apt:
    update_cache: yes
    name: nfs-common
    state: present

- name: Create mountable dir
  file: 
    path: "{{ mountable_dir }}"
    state: directory  

- name: Copy fstab file to host
  template:
    src: fstab
    dest: /etc/fstab

- name: Reload fstab config
  command: mount -a