- name: Ensure required packages for nfs server are installed
  apt:
    update_cache: yes
    name: nfs-kernel-server
    state: present

- name: Create mountable dir
  file: 
    path: "{{ mountable_dir }}"
    state: directory

- name: Copy exports file to host
  template:
    src: exports
    dest: /etc/exports

- name: Reload nfs server
  command: exportfs -ra