- name: Import repository key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian xenial main erlang"
    filename: "bintray.rabbitmq"
    update_cache: yes
    state: present

- name: install required packages
  apt:
    update_cache: yes
    force: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server
