- name: Ensure registartor container is started and optionally recreated ({{ docker_recreate }})
  docker_container:
    name: "{{ app_name }}"
    image: gliderlabs/registrator:master
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    network_mode: host
    restart_policy: unless-stopped
    state: started
    recreate: "{{ docker_recreate }}"
    command: -internal -cleanup=true -useIpFromLabel host.ip consul://{{ consul_agent_ip }}:8500 
