- name: Wait for rabbitmq to start
  pause:
    seconds: 5

- name: Run test image (Competing Consumers)
  docker_container:
    name: testimage_cc
    image: inowas/rabbitmq-test
    networks:
      - name: jobmanager_network
    env:
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: "{{ admin_user_password }}"
    command: test_script_cc.py
    restart: yes
    detach: no
    interactive: yes
    pull: yes

- name: Run test image (Remote Procedure Call)
  docker_container:
    name: testimage_rpc
    image: inowas/rabbitmq-test
    networks:
      - name: jobmanager_network
    env:
      RABBITMQ_HOSTNAME: agent-jobmanager.node.consul
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: "{{ admin_user_password }}"
    command: test_script_rpc.py
    restart: yes
    detach: no
    interactive: yes
    pull: yes