- name: Wait for rabbitmq to start
  pause:
    seconds: 20

- name: Run test image (Competing Consumers)
  docker_container:
    name: testimage_cc
    image: inowas/rabbitmq-test
    env:
      RABBITMQ_HOSTNAME: rabbitmq-tcp.service.consul
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: "{{ admin_user_password }}"
    dns_servers:
    - "{{ consul_agent_ip }}"
    command: test_script_cc.py
    restart: yes
    detach: no
    interactive: yes
    pull: yes

- name: Run test image (Remote Procedure Call)
  docker_container:
    name: testimage_rpc
    image: inowas/rabbitmq-test
    env:
      RABBITMQ_HOSTNAME: rabbitmq-tcp.service.consul
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: "{{ admin_user_password }}" 
    dns_servers:
    - "{{ consul_agent_ip }}"
    command: test_script_rpc.py
    restart: yes
    detach: no
    interactive: yes
    pull: yes 