global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    scrape_interval: 1s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['rabbitmq.service.consul:15672']

  - job_name: 'docker'
    scrape_interval: 1s
    static_configs:
      - targets: ['agent-nfs.node.consul:9323', 'agent-worker-node-1.node.consul:9323', 'agent-monitoring.node.consul:9323', 'agent-jobmanager.node.consul:9323', 'agent-dns.node.consul:9323']
  
  - job_name: 'nodes'
    scrape_interval: 1s
    static_configs:
      - targets: ['agent-nfs.node.consul:9100', 'agent-worker-node-1.node.consul:9100', 'agent-monitoring.node.consul:9100', 'agent-jobmanager.node.consul:9100', 'agent-dns.node.consul:9100']